### ISSUE TITLE
调用云悉查指纹查不到使用的是什么cms

### ISSUE THREAD

**Issue by cwkiller** [teamssix/pigat#3]
![image](https://user-images.githubusercontent.com/19302055/69725525-5986f600-1159-11ea-9fbd-8db8fe09c060.png)
![image](https://user-images.githubusercontent.com/19302055/69725780-e9c53b00-1159-11ea-9e73-8c99fb226ed3.png)

**Comment by teamssix** [comment]
你好，请问你查询的是那个URL呢？我需要用这个URL进行调试，因为我平时使用的过程中没有碰到这个问题

**Comment by cwkiller** [comment]
http://www.fmetro.net/




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TeamsSix"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 上午9:08
收件人:&nbsp;"teamssix/Passive-Intelligence-Gathering-Aggregation-Tool"<Passive-Intelligence-Gathering-Aggregation-Tool@noreply.github.com&gt;;
抄送:&nbsp;"求醉ヽ不醒- "<757953678@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [teamssix/Passive-Intelligence-Gathering-Aggregation-Tool] 调用云悉查指纹查不到使用的是什么cms (#3)




你好，请问你查询的是那个URL呢？我需要用这个URL进行调试，因为我平时使用的过程中没有碰到这个问题

**Comment by teamssix** [comment]
好的,我这边看看处理一下,感谢反馈

**Comment by xiaotong-wwq** [comment]
nb
