### ISSUE TITLE
sh: 1: scrapy: not found 这个报错是需要安装scrapy吗

### ISSUE THREAD

**Issue by liutuo008** [teamssix/pigat#5]
sh: 1: scrapy: not found

**Comment by teamssix** [comment]
是的，你需要先安装Scrapy库，你可以运行以下命令安装Scrapy，但这不是建议的做法：
```
pip3 install Scrapy
```
建议运行下面的命令以确保所有第三方模块都被安装，避免再次出现类似异常报错：
```
pip3 install -r requirements.txt
```
如果运行起来比较慢，可以尝试下面的命令，利用国内源提高下载安装库的速度：
```
pip3 install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/
```

**Comment by liutuo008** [comment]
这个后来弄好了，因为没在pigta目录安装黄金，装了个mangob重启了系统进不去了😃




| |
刘拓
|
|
邮箱：liutuo008@163.com
|

签名由 网易邮箱大师 定制

在2020年03月28日 17:59，TeamsSix 写道：

是的，你需要先安装Scrapy库，你可以运行以下命令安装Scrapy，但这不是建议的做法：

pip3 install Scrapy


建议运行下面的命令以确保所有第三方模块都被安装，避免再次出现类似异常报错：

pip3 install -r requirements.txt


如果运行起来比较慢，可以尝试下面的命令，利用国内源提高下载安装库的速度：

pip3 install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/

**Comment by liutuo008** [comment]
作者你好，你没尝试把这个加到快捷方式里，在根目录 pigat可以直接使用这样




| |
刘拓
|
|
邮箱：liutuo008@163.com
|

签名由 网易邮箱大师 定制

在2020年03月28日 18:00，刘拓 写道：
这个后来弄好了，因为没在pigta目录安装黄金，装了个mangob重启了系统进不去了😃




| |
刘拓
|
|
邮箱：liutuo008@163.com
|

签名由 网易邮箱大师 定制

在2020年03月28日 17:59，TeamsSix 写道：

是的，你需要先安装Scrapy库，你可以运行以下命令安装Scrapy，但这不是建议的做法：

pip3 install Scrapy


建议运行下面的命令以确保所有第三方模块都被安装，避免再次出现类似异常报错：

pip3 install -r requirements.txt


如果运行起来比较慢，可以尝试下面的命令，利用国内源提高下载安装库的速度：

pip3 install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/

**Comment by teamssix** [comment]
你的意思我理解，感谢你提的建议，后期我会考虑的，谢谢。

**Comment by liutuo008** [comment]
建议：
1，添加扫描网站基础信息
2，旁站扫描
3，端口扫描
4，敏感信息泄露网址





| |
刘拓
|
|
邮箱：liutuo008@163.com
|

签名由 网易邮箱大师 定制

在2020年03月28日 23:14，刘拓 写道：
作者你好，你没尝试把这个加到快捷方式里，在根目录 pigat可以直接使用这样




| |
刘拓
|
|
邮箱：liutuo008@163.com
|

签名由 网易邮箱大师 定制

在2020年03月28日 18:00，刘拓 写道：
这个后来弄好了，因为没在pigta目录安装黄金，装了个mangob重启了系统进不去了😃




| |
刘拓
|
|
邮箱：liutuo008@163.com
|

签名由 网易邮箱大师 定制

在2020年03月28日 17:59，TeamsSix 写道：

是的，你需要先安装Scrapy库，你可以运行以下命令安装Scrapy，但这不是建议的做法：

pip3 install Scrapy


建议运行下面的命令以确保所有第三方模块都被安装，避免再次出现类似异常报错：

pip3 install -r requirements.txt


如果运行起来比较慢，可以尝试下面的命令，利用国内源提高下载安装库的速度：

pip3 install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/
