### ISSUE TITLE
大佬帮忙解决下，运行之后会先出现一些小乱码，然后给出提示信息然后才可以用，-o功能不能使用

### ISSUE THREAD

**Issue by lwx1125** [teamssix/pigat#6]
### 

- 
![1](https://user-images.githubusercontent.com/55575103/79717582-a20f9d80-830c-11ea-8bf3-7c0a45601af2.png)
![2](https://user-images.githubusercontent.com/55575103/79717600-ae93f600-830c-11ea-9793-f99fc504910e.png)
![6](https://user-images.githubusercontent.com/55575103/79717671-e1d68500-830c-11ea-82c5-914c777fd61d.png)
![7](https://user-images.githubusercontent.com/55575103/79717696-f3b82800-830c-11ea-9b13-2420f9766594.png)

**Comment by lwx1125** [comment]
6那个被动收集子域名shodan信息也不好使

**Comment by teamssix** [comment]
没看懂您的问题

**Comment by teamssix** [comment]
> 6那个被动收集子域名shodan信息也不好使

Shodan收集模块的结果多少取决于IP收集模块的结果多少。

如果对于Shodan信息收集模块有什么好的建议，欢迎提出啊。

**Comment by lwx1125** [comment]
就是程序运行之后左侧会出现一些小乱码

就这样子如果我输入1的话就会出现这样子

正常来说程序运行之后不是应该直接出现像图二一样那种嘛，为什么我会有图一这样，输入命令之后才会出现图二这样，这是什么原因呢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TeamsSix"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月20日(星期一) 中午1:50
收件人:&nbsp;"teamssix/pigat"<pigat@noreply.github.com&gt;;
抄送:&nbsp;"痞子气??"<710378572@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [teamssix/pigat] 大佬帮忙解决下，运行之后会先出现一些小乱码，然后给出提示信息然后才可以用，-o功能不能使用 (#6)





 
没看懂您的问题

**Comment by lwx1125** [comment]
大佬看懂了吗，方便的话可以加个qq聊么

**Comment by teamssix** [comment]
1、建议在电脑的终端中运行一下试试，比如CMD或者PowerShell。因为我刚才测试了一下没有发现“乱码”的问题

2、另外确认一下下载的版本是否是最新版本
